using CodeWalker.GameFiles;

namespace grzyClothTool.Optimization.Lods;

/// <summary>A drawable of a .ydd whose High LOD exists but Medium and/or Low are missing.</summary>
public sealed record MissingLods(int Index, string Name, IReadOnlyList<LodLevel> Levels, int HighTriangles);

/// <summary>Triangle count of every LOD of one drawable of a .ydd, as the file was read (0 = LOD absent).</summary>
public sealed record DrawableStats(string Name, int HighTriangles, int MediumTriangles, int LowTriangles, int VeryLowTriangles);

/// <summary>
/// Finds drawables without LODs and copies LOD models generated by Sollumz back into the original .ydd.
/// Only the new Medium/Low models are taken from the Sollumz export: textures, shaders, the High model and every
/// other part of the original file stay exactly as they were.
/// </summary>
public static class LodGrafter
{
    public static IReadOnlyList<MissingLods> FindMissing(YddFile ydd)
    {
        var result = new List<MissingLods>();
        var drawables = ydd.DrawableDict?.Drawables?.data_items ?? [];

        for (int i = 0; i < drawables.Length; i++)
        {
            var models = drawables[i]?.DrawableModels;
            int highTriangles = CountTriangles(models?.High);
            if (highTriangles == 0)
            {
                continue;
            }

            var levels = new List<LodLevel>();
            if (CountTriangles(models!.Med) == 0) levels.Add(LodLevel.Medium);
            if (CountTriangles(models.Low) == 0) levels.Add(LodLevel.Low);

            if (levels.Count > 0)
            {
                result.Add(new MissingLods(i, NameOf(drawables[i], i), levels, highTriangles));
            }
        }

        return result;
    }

    public static IReadOnlyList<DrawableStats> Describe(YddFile ydd)
    {
        var drawables = ydd.DrawableDict?.Drawables?.data_items ?? [];
        var result = new List<DrawableStats>(drawables.Length);
        for (int i = 0; i < drawables.Length; i++)
        {
            var models = drawables[i]?.DrawableModels;
            result.Add(new DrawableStats(NameOf(drawables[i], i), CountTriangles(models?.High), CountTriangles(models?.Med),
                CountTriangles(models?.Low), CountTriangles(models?.VLow)));
        }
        return result;
    }

    // Models read from XML only have the count on the index buffer; DrawableGeometry.IndicesCount is set on write.
    public static int CountTriangles(DrawableModel[]? models) =>
        models?.Sum(m => m?.Geometries?.Sum(g => (int)(g?.IndexBuffer?.IndicesCount ?? g?.IndicesCount ?? 0) / 3) ?? 0) ?? 0;

    /// <summary>Copies the missing LOD levels from <paramref name="generated"/> into <paramref name="ydd"/>.</summary>
    public static List<LodChange> Graft(YddFile ydd, IReadOnlyList<MissingLods> missing, YddFile generated, List<string> notes)
    {
        var changes = new List<LodChange>();
        var originals = ydd.DrawableDict!.Drawables.data_items;
        var generatedDrawables = generated.DrawableDict?.Drawables?.data_items ?? [];

        foreach (var entry in missing)
        {
            var original = originals[entry.Index];
            var source = FindGenerated(generatedDrawables, entry, originals.Length);
            if (source == null)
            {
                notes.Add($"{entry.Name}: not found in the Sollumz export; LODs not added");
                continue;
            }

            var shaderMap = MapShaders(source.ShaderGroup, original.ShaderGroup);
            if (shaderMap == null)
            {
                notes.Add($"{entry.Name}: Sollumz changed the shaders, LODs not added");
                continue;
            }

            foreach (var level in entry.Levels)
            {
                var models = level == LodLevel.Medium ? source.DrawableModels?.Med : source.DrawableModels?.Low;
                int triangles = CountTriangles(models);
                if (models == null || triangles == 0)
                {
                    notes.Add($"{entry.Name}: Sollumz did not generate the {level} LOD");
                    continue;
                }

                if (!AdaptModels(models, original, shaderMap))
                {
                    notes.Add($"{entry.Name}: generated {level} LOD uses a shader missing from the original; not added");
                    continue;
                }

                var issues = LodValidator.ValidateModels(models, original.DrawableModels!.High,
                    original.ShaderGroup?.Shaders?.data_items?.Length ?? 0, entry.Name, level.ToString(), generated: true);
                var errors = issues.Where(i => i.Severity == LodIssueSeverity.Error).ToList();
                if (errors.Count > 0)
                {
                    notes.Add($"{entry.Name}: generated {level} LOD failed validation, not added: {Summarize(errors)}");
                    continue;
                }
                if (issues.Count > 0)
                {
                    notes.Add($"{entry.Name}: generated {level} LOD warnings: {Summarize(issues)}");
                }

                original.DrawableModels ??= new DrawableModelsBlock();
                if (level == LodLevel.Medium)
                {
                    original.DrawableModels.Med = models;
                    original.FlagsMed = original.FlagsHigh;
                }
                else
                {
                    original.DrawableModels.Low = models;
                    original.FlagsLow = original.FlagsHigh;
                }

                changes.Add(new LodChange(entry.Name, level, entry.HighTriangles, triangles));
            }

            original.BuildRenderMasks();
            original.BuildAllModels();
            original.BuildVertexDecls();
            original.AssignGeometryShaders(original.ShaderGroup);
        }

        return changes;
    }

    private static Drawable? FindGenerated(Drawable[] generated, MissingLods entry, int originalCount)
    {
        var byName = generated.FirstOrDefault(d => string.Equals(NameOf(d, -1), entry.Name, StringComparison.OrdinalIgnoreCase));
        if (byName != null)
        {
            return byName;
        }

        // Unresolved names (hash#dd) are renamed by Sollumz; fall back to the position when nothing was added or removed.
        return generated.Length == originalCount ? generated[entry.Index] : null;
    }

    /// <summary>Sollumz may write shaders in another order; maps each exported shader index to the original one.</summary>
    internal static ushort[]? MapShaders(ShaderGroup? exported, ShaderGroup? original)
    {
        var exportedShaders = exported?.Shaders?.data_items ?? [];
        var originalShaders = original?.Shaders?.data_items ?? [];
        var map = new ushort[exportedShaders.Length];
        var used = new bool[originalShaders.Length];

        for (int i = 0; i < exportedShaders.Length; i++)
        {
            var signature = Signature(exportedShaders[i]);
            int match = -1;

            // Same position first (the usual case), then the first unused shader with the same signature.
            if (i < originalShaders.Length && !used[i] && Signature(originalShaders[i]) == signature)
            {
                match = i;
            }
            for (int j = 0; match < 0 && j < originalShaders.Length; j++)
            {
                if (!used[j] && Signature(originalShaders[j]) == signature)
                {
                    match = j;
                }
            }

            if (match < 0)
            {
                return null;
            }

            used[match] = true;
            map[i] = (ushort)match;
        }

        return map;
    }

    private static string Signature(ShaderFX? shader)
    {
        if (shader == null)
        {
            return "";
        }

        var textures = (shader.ParametersList?.Parameters ?? [])
            .Select(p => (p.Data as TextureBase)?.Name?.ToLowerInvariant())
            .Where(n => !string.IsNullOrEmpty(n))
            .Order(StringComparer.Ordinal);

        return $"{shader.FileName.Hash}|{string.Join(",", textures)}";
    }

    /// <summary>Points the generated models to the original shaders and gives them the High model's skin binding.</summary>
    private static bool AdaptModels(DrawableModel[] models, Drawable original, ushort[] shaderMap)
    {
        var highModels = original.DrawableModels!.High;

        for (int m = 0; m < models.Length; m++)
        {
            var model = models[m];
            var geometries = model.Geometries ?? [];
            var template = highModels[Math.Min(m, highModels.Length - 1)];

            // Sollumz exports ped components without a skeleton, so it cannot know they are skinned.
            model.SkeletonBinding = template.SkeletonBinding;
            model.RenderMaskFlags = template.RenderMaskFlags;

            var templateBoneIds = template.Geometries?
                .Where(g => g?.BoneIds is { Length: > 0 })
                .SelectMany(g => g.BoneIds)
                .ToList() ?? [];

            model.ShaderMapping = new ushort[geometries.Length];
            for (int g = 0; g < geometries.Length; g++)
            {
                var geometry = geometries[g];
                if (geometry.ShaderID >= shaderMap.Length)
                {
                    return false;
                }

                geometry.ShaderID = shaderMap[geometry.ShaderID];
                model.ShaderMapping[g] = geometry.ShaderID;

                // The exported blend indices are the skeleton bone indices themselves (the worker maps the
                // UNKNOWN_BONE.<n> groups back to n), which is what an identity bone table describes; this is also
                // what Sollumz writes when it exports with a skeleton.
                if ((geometry.BoneIds == null || geometry.BoneIds.Length == 0) && templateBoneIds.Count > 0)
                {
                    int count = templateBoneIds.Max() + 1;
                    geometry.BoneIds = Enumerable.Range(0, count).Select(i => (ushort)i).ToArray();
                }
            }
        }

        return true;
    }

    private static string Summarize(List<LodIssue> issues) =>
        string.Join("; ", issues.Take(3).Select(i => i.Message)) + (issues.Count > 3 ? $" (+{issues.Count - 3} more)" : "");

    private static string NameOf(Drawable? drawable, int index)
    {
        var name = drawable?.Name;
        if (string.IsNullOrEmpty(name))
        {
            return index >= 0 ? $"drawable {index}" : "";
        }
        return name.EndsWith("#dd", StringComparison.OrdinalIgnoreCase) ? name[..^3] : name;
    }
}
